# GT4Py - GridTools Framework
#
# Copyright (c) 2014-2024, ETH Zurich
# All rights reserved.
#
# Please, refer to the LICENSE file in the root directory.
# SPDX-License-Identifier: BSD-3-Clause

import pytest
import copy

dace = pytest.importorskip("dace")

from gt4py.next.program_processors.runners.dace import (
    transformations as gtx_transformations,
)
from dace.sdfg import nodes as dace_nodes, propagation as dace_propagation
from sympy.core.numbers import Number

from . import util


def _make_sdfg_with_multiple_maps_that_share_inputs_small(
    N: str | int,
) -> dace.SDFG:
    """
    Create a SDFG with multiple maps that share inputs and outputs.
    The SDFG has originally 4 maps:
    - The first map has multiple tasklets and a nested map.
    - The second, third and fourth map have a single tasklet.
    The some of the maps share inputs with each other.
    The SDFG has the following inputs and outputs:
    - Inputs: a[i, j], b[i, j], c[i, j], d[i, j]
    - Outputs: out1[i, j], out2[i, j], out3[i, j], out4[i, j]
    """
    shape = (N, N)
    sdfg = dace.SDFG(util.unique_name("multiple_maps"))
    state = sdfg.add_state(is_start_block=True)

    for name in ["a", "b", "c", "d", "out1", "out2", "out3"]:
        sdfg.add_array(
            name=name,
            shape=shape,
            dtype=dace.float64,
            transient=False,
        )

    # sdfg.add_scalar("tmp1", dtype=dace.float64, transient=True)
    # sdfg.add_scalar("tmp2", dtype=dace.float64, transient=True)
    # sdfg.add_scalar("tmp3", dtype=dace.float64, transient=True)
    # sdfg.add_scalar("tmp4", dtype=dace.float64, transient=True)
    # a, b, out1, tmp1, tmp2, tmp3, tmp4 = (
    #     state.add_access(name) for name in ["a", "b", "out1", "tmp1", "tmp2", "tmp3", "tmp4"]
    # )
    sdfg.add_symbol("horizontal_start", dace.int32)
    sdfg.add_symbol("horizontal_end", dace.int32)

    state.add_mapped_tasklet(
        name="first_computation",
        map_ranges=[("i", f"0:{N//2}"), ("j", "horizontal_start:horizontal_end")],
        inputs={"__in0": dace.Memlet("a[i, j]"), "__in1": dace.Memlet("b[i, j]")},
        code="__out = __in0 + __in1 + 1.0",
        outputs={"__out": dace.Memlet("out1[i, j]")},
        external_edges=True,
    )

    state.add_mapped_tasklet(
        name="second_computation",
        map_ranges=[("i", f"{N//2}:{(N//2)+2}"), ("j", "horizontal_start:horizontal_end")],
        inputs={"__in0": dace.Memlet("b[i, j]"), "__in1": dace.Memlet("c[i, j]")},
        code="__out = __in0 + __in1 + 1.0",
        outputs={"__out": dace.Memlet("out2[i, j]")},
        external_edges=True,
    )

    state.add_mapped_tasklet(
        name="third_computation",
        map_ranges=[("i", f"{(N//2)+1}:{N}"), ("j", "horizontal_start:horizontal_end")],
        inputs={"__in0": dace.Memlet("c[i, j]"), "__in1": dace.Memlet("d[i, j]")},
        code="__out = __in0 + __in1 + 2.0",
        outputs={"__out": dace.Memlet("out3[i, j]")},
        external_edges=True,
    )

    existing_access_nodes = {}

    # Remove duplicate access nodes which get generated by the above maps
    for access_node in state.nodes():
        if isinstance(access_node, dace_nodes.AccessNode):
            if access_node.label not in existing_access_nodes:
                existing_access_nodes[access_node.label] = access_node
            else:
                edges_for_removal = []
                for edge in state.in_edges(access_node):
                    edges_for_removal.append(edge)
                    state.add_edge(
                        edge.src,
                        edge.src_conn,
                        existing_access_nodes[access_node.label],
                        edge.dst_conn,
                        copy.deepcopy(edge.data),
                    )
                for edge in state.out_edges(access_node):
                    edges_for_removal.append(edge)
                    state.add_edge(
                        existing_access_nodes[access_node.label],
                        edge.src_conn,
                        edge.dst,
                        edge.dst_conn,
                        copy.deepcopy(edge.data),
                    )
                for edge in edges_for_removal:
                    state.remove_edge(edge)
                state.remove_node(access_node)

    dace_propagation.propagate_states(sdfg)
    sdfg.validate()

    return sdfg


def test_horizontal_map_fusion():
    N = 40
    sdfg = _make_sdfg_with_multiple_maps_that_share_inputs_small(N)
